version : '1'

services :
	soa:
		image: sameersbn/bind:latest
		container_name: soa
	ports:
	- "53:53/tcp"
	- "53:53/udp"
	volumes:
		- ./config/named.conf:/etc/bind/named.conf
		- ./config/named.conf.options:/etc/bind/named.conf.options
		- ./config/named.conf.default-zones:/etc/bind/named.conf.default-zones
		- ./config/named.conf.local:/etc/bind/named.conf.local
		- ./config/db.wt6.ephec-ti.be:/etc/bind/db.wt6.ephec-ti.be
		- ./config/db.126.147.77.51:/etc/bind/db.126.126.147.77.51

