version: '3'

services:
 mail:
  image: mail:latest
  container_name: mail
  restart: always
  ports:
   - "25:25"
   - "110:110"
   - "143:143"
   - "465:465"
   - "587:587"
   - "993:993"
   - "995:995"
